
export const LOG_IN = 'LOG_IN';

export const REGISTER = 'REGISTER';

export const ADD_QUESTION = 'ADD_QUESTION';

export const ADD_ANSWER = 'ADD_ANSWER';

export const RETRIVE_USERS_DATA = 'RETRIVE_USERS_DATA';

export const SET_ALL_QUESTIONS_ARR = 'SET_ALL_QUESTIONS_ARR';

export const CHANGE_DISPLAYED_QUESTIONS = 'CHANGE_DISPLAYED_QUESTIONS';

export const GET_ALL_ANSWERS_OF_SPECIFIC_QUESTION = 'GET_ALL_ANSWERS_OF_SPECIFIC_QUESTION';